### ISSUE TITLE
Profile  page layout concern (responsive?)

### ISSUE THREAD

**Issue by WendyPorter** [JeromeFitz/react-instafeed#25]
When I view the profile page on my macbook air I see the company overview on the left hand side and Why Work with us is directly below the overview.  It looks like its going into responsive mode.  The Why Work with us and Company Perks etc should be showing on the right hand side.  Maybe the responsive settings are off?  I would expect this behavior on my phone but not on my macbook air?

**Comment by glawson** [comment]
@WendyPorter - I don't believe this is not the repo you wanted to create a new issue in :)   Please close.

**Comment by WendyPorter** [comment]
yep wrong repo sorry
