### ISSUE TITLE
The images are repeated several times

### ISSUE THREAD

**Issue by vdelianny** [JeromeFitz/react-instafeed#26]
Hello, I add this in my code and the images are repeated many times so add a limit.

`<Instafeed

    limit='2'

    resolution='standard_resolution'

    get='user'

    userId='xxxxxxxx'

    sortBy='none'

    clientId='xxxxxxxxxx'

    accessToken='xxxxxxxxxxxxxxx'

    template='<div class="instafeed-item">
                         <a href="{{link}}" target="_blank">
                            <img class="col-lg-6 col-xs-12" src="{{image}}" />
                         </a>
                   </div>'
 />`

**Comment by JeromeFitz** [comment]
Please see #24
