### ISSUE TITLE
Instagram API limit

### ISSUE THREAD

**Issue by raphaelfabeni** [JeromeFitz/react-instafeed#34]
Hey guys! How are you?
A question, maybe off-topic, but with some relation with the lib. Currently, the Instagram API has a limit of 500 requests per hour.  I was thinking if there is a way we can `cache` locally the current picture or if there is another way to avoid multiple requests for the same picture.
As I said, this issue is more about getting new ideas than about a lib problem.

**Comment by wesvance** [comment]
@raphaelfabeni How'd you go about fixing this? I'm having a similar issue and would love to know how you did it :D
