### ISSUE TITLE
Uncaught Error: Missing clientId or accessToken.

### ISSUE THREAD

**Issue by officialdrafty** [JeromeFitz/react-instafeed#5]
I have added a clientId or accessToken but still not working.  Every time I try to refresh my browser this two error message pop up in the console

```
warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

```
instafeed.js:42 Uncaught Error: Missing clientId or accessToken.
    at Instafeed.run (instafeed.js:42)
    at InstafeedComponent.render (index.js:52)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:362)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:238)

```

**Comment by JeromeFitz** [comment]
@brandonpowell In `0.3.0` we've updated the packages and fixed the deprecation warning specifically for `PropTypes`.

The README got a rewrite on how the Component should be accessed as well.

Please pull down the latest version and please let me know if you run into any issues after going through the updates in the README. It looks like your `clientId` and `accessToken` are not being passed still.

**Comment by officialdrafty** [comment]
@JeromeFitz I have a quick question: So I install the babel-plugin-transform-define and now do I have to create `.babelrc` file store `clientId` and `accessToken` still a beginner could explain to, please.

**Comment by JeromeFitz** [comment]
@brandonpowell I took a look at your repo and have a few suggestions.

#### `./src/index.js`
Remove this line
```javascript
import Instafeed from 'react-instafeed';
```
Change the following:

*Before:*
```javascript
        <Instafeed>
            <Gallery />
        </Instafeed>
```
*After:*
```javascript
        <Gallery />
```

#### `./src/instagram/image_feed.js`
Swap out for this code (from updated README):
```javascript
import React from 'react';
import Instafeed from 'react-instafeed';

class InstafeedComponent extends React.Component {
  render() {
    const instafeedTarget = 'instafeed';
    return (
      <div id={instafeedTarget}>
        <Instafeed
          limit='5'
          ref='instafeed'
          resolution='standard_resolution'
          sortBy='most-recent'
          target={instafeedTarget}
          template=''
          userId='userIdInstagramApiString'
          clientId='clientIdInstagramApiString'
          accessToken='accessTokenInstagramApiString'
          />
      </div>
    )

  }
}

export default InstafeedComponent;
```

#### react-scripts
I see you are using `react-scripts` they allow for you to pass ENVIRONMENT VARIABLES to the React Application as long as you prepend them with `REACT_APP_`.

So in your case I'd edit (or add):
#### `./.env`
```javascript
REACT_APP_INSTAGRAM_USER_ID=123...
REACT_APP_INSTAGRAM_CLIENT_ID=1f23...
REACT_APP_INSTAGRAM_ACCESS_TOKEN=123...1f23...

```
Your `.gitignore` settings ensure it will not be put in your repo. :octocat: 

Then you can go back to `./src/instagram/image_feed.js` and make the necessary edits:
```
          userId={process.env.REACT_APP_INSTAGRAM_USER_ID}
          clientId={process.env.REACT_APP_INSTAGRAM_CLIENT_ID}
          accessToken={process.env.REACT_APP_INSTAGRAM_ACCESS_TOKEN}
```

**Comment by officialdrafty** [comment]
@JeromeFitz Thank you for explaining to me

**Comment by JeromeFitz** [comment]
And thank you @brandonpowell for helping so much with the README and implementation of this in general. The updates for `0.3.x` were from your Issues and Troubleshooting. 😁️
