### ISSUE TITLE
 Uncaught Error: Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by officialdrafty** [JeromeFitz/react-instafeed#6]
I have found another error message access_token provided is invalid. I have looked and saw that Instagram changed their API on June 1, 2013, and didn't update their repo in instafeed.js.

```
instafeed.js:81 Uncaught Error: Error from Instagram: The access_token provided is invalid.
    at Instafeed.parse (instafeed.js:81)
    at recent?access_token=7605dba…&count=1&callback=instafeedCache1cab7d4b14b1467…:1
```

**Comment by JeromeFitz** [comment]
I forked your Repo, put the changes in from #5.

Please review the Pull Request.

You may have different code on your local machine, however, with #5 and the differences in the Pull Request this should hopefully get you to where you are looking to go.

**Comment by JeromeFitz** [comment]
Closing this issue based on updates you've made to your repo. If this needs to be re-opened please do. Good luck.
